In [80]:
import pandas as pd

In [81]:
data = {
    'name' : ['Ana', 'Bruno', 'Carla', 'Diego'],
    'age' : [23, 35, 29, 41],
    'city' : ['Uberlandia', 'Sao Paulo', 'Uberlandia', 'Belo Horizonte']
}

In [82]:
df = pd.DataFrame(data)

In [83]:
df['job'] = ['Engineer', 'Analyst', 'Engineer', 'Analyst']

In [84]:
df.groupby('city')['age'].agg(['mean', 'min', 'max'])

                mean  min  max
city
Belo Horizonte  41.0   41   41
Sao Paulo       35.0   35   35
Uberlandia      26.0   23   29

In [85]:
df.groupby('city')['age'].mean().sort_values(ascending=False).head(1)

city
Belo Horizonte    41.0
Name: age, dtype: float64

In [86]:
salaries = {
    'name': ['Ana', 'Bruno', 'Carla', 'Diego'],
    'salary': [4500, 6200, 5100, 7000]
}
df_salaries = pd.DataFrame(salaries)

In [87]:
extra_salaries = {
    'name': ['Ana', 'Bruno', 'Carla'],
    'salary': [4500, 6200, 5100]
}
df_extra = pd.DataFrame(extra_salaries)
result_outer = df.merge(df_extra, on='name', how ='outer')
result_outer

    name  age            city       job  salary
0    Ana   23      Uberlandia  Engineer  4500.0
1  Bruno   35       Sao Paulo   Analyst  6200.0
2  Carla   29      Uberlandia  Engineer  5100.0
3  Diego   41  Belo Horizonte   Analyst     NaN

In [95]:
extra_salaries2 = {
    'name': ['Ana', 'Bruno', 'Carla', 'Eduardo'],
    'salary': [4500, 6200, 5100,8000]
}
df_extra2 = pd.DataFrame (extra_salaries2)
result_left2 = df.merge(df_extra2, on='name', how='left')
result_left2['salary'] = result_left2['salary'].fillna(result_left2['salary'].mean())
result_left2

    name  age            city       job       salary
0    Ana   23      Uberlandia  Engineer  4500.000000
1  Bruno   35       Sao Paulo   Analyst  6200.000000
2  Carla   29      Uberlandia  Engineer  5100.000000
3  Diego   41  Belo Horizonte   Analyst  5266.666667

In [96]:
merged = df.merge(df_salaries, on='name')
merged

    name  age            city       job  salary
0    Ana   23      Uberlandia  Engineer    4500
1  Bruno   35       Sao Paulo   Analyst    6200
2  Carla   29      Uberlandia  Engineer    5100
3  Diego   41  Belo Horizonte   Analyst    7000